const app = document.querySelector("#app");
const navigation = document.querySelector(".bottom-nav");
const historyKey = "ground-force-workout-history";

const exercise = (name, reps, description, cue, tip, equipment = "Bodyweight") => ({
  id: name.toLowerCase().replaceAll(/[^a-z0-9]+/g, "-").replaceAll(/(^-|-$)/g, ""), name, reps, description, cue, tip, equipment, image: null,
});
const common = {
  reset: () => exercise("Breathing Reset", "4 slow breaths", "Lie on your back with feet supported and breathe slowly into your ribs.", "Let your ribs settle as you exhale.", "Keep this easy; stop or change position if symptoms increase."),
  hipMobility: () => exercise("Hip Mobility Flow", "45 sec per side", "Move through a comfortable hip rotation and half-kneeling hip-flexor stretch.", "Use a quiet range with a level pelvis.", "Do not force range or chase a stretch."),
  bridge: (reps = "2 × 8") => exercise("Glute Bridge", reps, "Press through both feet to lift your hips, then lower with control.", "Keep the pelvis level and feel both glutes working.", "Shorten the range if hamstrings or back take over."),
  hipThrust: (reps = "3 × 8") => exercise("Hip Thrust", reps, "With upper back supported on a bench, raise the hips until the trunk and thighs align.", "Pause at the top without arching your low back.", "Add load only after the same smooth position is repeatable.", "Bench and optional load"),
  birdDog: (reps = "2 × 6 per side") => exercise("Bird Dog", reps, "From hands and knees, reach the opposite arm and leg long, then return without shifting.", "Keep your pelvis level and your trunk still.", "Make the reach smaller if you rotate or symptoms increase."),
  deadBug: (reps = "2 × 6 per side") => exercise("Dead Bug", reps, "From your back, slowly lower the opposite arm and leg, then return.", "Exhale and keep your low back comfortably heavy on the floor.", "Use a shorter lever to keep control."),
  sidePlank: (reps = "2 × 15 sec per side", elevated = true) => exercise(elevated ? "Side Plank from Knees" : "Side Plank", reps, "Hold a straight line from shoulder through hips while braced on your forearm.", "Keep ribs stacked over a level pelvis.", "Use the knee-supported or elevated version if you lose position."),
  pallof: (reps = "2 × 8 per side") => exercise("Anti-Rotation Press", reps, "Press a band or cable straight out from your chest and return slowly.", "Resist turning toward the anchor.", "Choose a light resistance that lets the pelvis stay quiet.", "Band or cable"),
  balance: (reps = "2 × 20 sec per side") => exercise("Single-Leg Balance", reps, "Stand on one foot with a soft knee and free foot hovering.", "Keep the pelvis level; let the foot tripod stay connected.", "Use a fingertip support before adding difficulty."),
  stepDown: (reps = "2 × 6 per side", height = "low") => exercise("Controlled Step-Down", reps, `Stand on a ${height} step and slowly tap the free heel to the floor before returning.`, "Track the knee over the middle toes with a level pelvis.", "Reduce step height or range if you shift, pinch, or symptoms increase.", "Step or box"),
  splitSquat: (reps = "2 × 6 per side") => exercise("Split Squat", reps, "Lower straight down between your feet, then press through the front foot to stand.", "Keep the front knee tracking and pelvis square.", "Use support or a smaller range to keep the movement controlled."),
  rdl: (reps = "2 × 6 per side") => exercise("Single-Leg RDL", reps, "Hinge at the hip as the free leg reaches back, then stand by pressing the floor away.", "Keep hips level and reach long through the back leg.", "Use a wall touch or light support before adding load."),
  stepUp: (reps = "2 × 6 per side") => exercise("Controlled Step-Up", reps, "Step fully onto a low box and stand tall before lowering slowly.", "Drive through the working foot without pushing off the trailing leg.", "Use a lower box if the pelvis drops or the knee collapses.", "Step or box"),
  ringRow: (reps = "2 × 8") => exercise("Ring Row", reps, "Keep a long body line as you pull your chest toward the rings.", "Pull elbows toward ribs without shrugging.", "Walk feet back only when each rep stays smooth.", "Rings"),
  ringPushup: (reps = "2 × 6") => exercise("Ring Push-Up", reps, "Lower your chest between the rings, then press the rings away with control.", "Keep ribs, hips, and shoulders moving together.", "Raise the rings to reduce load and avoid compensation.", "Rings"),
  cleanPress: (reps = "3 × 5 per side") => exercise("Clean & Press", reps, "Using a manageable dumbbell or kettlebell, clean the weight to the rack with control, settle, then press smoothly overhead.", "Brace a stable trunk, receive a controlled catch, and make the transition from clean to press smooth.", "This is a strength and power movement, not conditioning. Do not force overhead range; stop or modify if shoulder symptoms increase.", "Dumbbell or kettlebell"),
  ringCurl: (reps = "2 × 8") => exercise("Ring Curl", reps, "With palms facing up, keep the upper arms still as you curl your hands toward your forehead, then lower slowly.", "Keep a long body line and let the elbows bend without the shoulders rolling forward.", "Walk feet forward only when the trunk stays controlled throughout.", "Rings"),
  barbellCurl: (reps = "2 × 8") => exercise("Barbell Curl (Optional)", reps, "Curl a light barbell from thighs toward shoulders, then lower under control.", "Keep ribs stacked and elbows close to your sides.", "Use rings instead if the barbell version encourages swinging or discomfort.", "Barbell"),
  ringTriceps: (reps = "2 × 8") => exercise("Ring Triceps Extension", reps, "With hands in the rings, bend the elbows to bring the hands near the forehead, then extend back to a long body line.", "Keep elbows pointing forward and trunk braced.", "Raise the rings or shorten the range if shoulder symptoms increase.", "Rings"),
  ringCloseGrip: (reps = "2 × 6") => exercise("Ring Close-Grip Push-Up", reps, "Set the rings close together, lower with elbows near your ribs, then press back with control.", "Keep shoulders, ribs, and hips moving as one unit.", "Raise the rings to reduce load; stop or modify if shoulder symptoms increase.", "Rings"),
  calfRaise: (reps = "2 × 10") => exercise("Calf Raise", reps, "Rise onto the balls of your feet, pause, and lower slowly.", "Keep pressure even through the big toe and heel.", "Use support and keep the range comfortable."),
  tibRaise: (reps = "2 × 10") => exercise("Tibialis Raise", reps, "With your back against a wall, lift the forefeet while heels stay down.", "Move slowly through the ankles.", "Use a smaller range if the front of the shin fatigues quickly."),
  carry: (reps = "2 × 20 sec per side", load = "light") => exercise("Suitcase Carry", reps, `Walk slowly with a ${load} weight on one side.`, "Stay tall with ribs stacked over a level pelvis.", "Use less load or a shorter walk if you lean or symptoms increase.", "One dumbbell or kettlebell"),
  farmerCarry: (reps = "2 × 25 sec") => exercise("Farmer Carry", reps, "Walk slowly while carrying matched light weights at your sides.", "Keep shoulders relaxed, steps quiet, and trunk tall.", "Load should support posture, never challenge it at the expense of control.", "Two dumbbells or kettlebells"),
  landing: (reps = "2 × 5") => exercise("Snap-Down Landing", reps, "Rise tall, then quickly settle into a quiet athletic landing without leaving the floor.", "Land softly with knees tracking and hips level.", "Stop if landing quality changes or symptoms increase."),
  pogo: (reps = "2 × 10") => exercise("Low Pogo Hops", reps, "Use small, quiet ankle hops in place with relaxed, springy contacts.", "Keep the hops low and land evenly through both feet.", "Return to calf raises if contacts become noisy or uncomfortable."),
  lateralStep: (reps = "2 × 8 per side") => exercise("Lateral Step-Up", reps, "Step sideways onto a low box and stand under control, then lower slowly.", "Keep the working knee aligned and pelvis level.", "Reduce height if you shift or lose balance.", "Step or box"),
};
const session = (day, type, title, estimatedDuration, objective, exercises) => ({ id: `restore-month-1-day-${day}`, day, type, title, subtitle: type, estimatedDuration, objective, exercises });
const days = [
  session(1,"Restore","Reset & Glute Awareness","20 min","Restore comfortable movement and introduce even glute activation.",[common.reset(),common.hipMobility(),common.bridge(),common.birdDog(),common.balance()]),
  session(2,"Stability","Foundation Trunk Control","25 min","Build a quiet trunk and level pelvis with basic stability work.",[common.deadBug(),common.sidePlank(),common.birdDog(),common.calfRaise(),common.hipMobility()]),
  session(3,"Recovery","Easy Mobility Reset","15 min","Practice comfortable mobility, breathing, and low-effort control.",[common.reset(),common.hipMobility(),common.bridge("2 × 6"),common.balance("2 × 15 sec per side")]),
  session(4,"Strength","Supported Lower Strength","30 min","Introduce controlled squat-pattern strength and upper-body pulling.",[common.bridge(),common.splitSquat(),common.stepUp(),common.ringRow(),common.deadBug()]),
  session(5,"Movement","Balance & Walking Control","20 min","Rehearse single-leg control without adding load.",[common.hipMobility(),common.balance(),common.stepDown("2 × 5 per side"),common.birdDog(),common.calfRaise()]),
  session(6,"Stability","Lateral Control Basics","25 min","Build lateral trunk and hip stability with careful positions.",[common.sidePlank(),common.pallof(),common.stepDown(),common.bridge(),common.tibRaise()]),
  session(7,"Recovery","Week 1 Recovery","15 min","Recover with easy mobility and a check-in on movement quality.",[common.reset(),common.hipMobility(),common.bridge("2 × 8"),common.deadBug("2 × 5 per side")]),
  session(8,"Stability","Single-Leg Foundation","25 min","Build stability before increasing unilateral range or load.",[common.balance("3 × 20 sec per side"),common.stepDown("2 × 6 per side"),common.sidePlank("2 × 20 sec per side"),common.pallof(),common.calfRaise("3 × 10")]),
  session(9,"Strength","Split Squat & Pull","30 min","Develop controlled unilateral strength and ring pulling.",[common.bridge("3 × 8"),common.splitSquat("3 × 6 per side"),common.ringRow("3 × 8"),common.stepUp("2 × 8 per side"),common.deadBug()]),
  session(10,"Movement","Hinge Pattern Practice","25 min","Learn a stable single-leg hinge with balance support as needed.",[common.hipMobility(),common.rdl("2 × 5 per side"),common.birdDog("2 × 8 per side"),common.balance(),common.tibRaise()]),
  session(11,"Recovery","Mobility & Control","15 min","Maintain comfortable range while letting fatigue settle.",[common.reset(),common.hipMobility(),common.sidePlank("2 × 15 sec per side"),common.calfRaise("2 × 8")]),
  session(12,"Strength","Unilateral Strength A","30 min","Progress unilateral strength through reps while keeping position stable.",[common.hipThrust("3 × 8"),common.splitSquat("3 × 7 per side"),common.stepDown("3 × 6 per side"),common.ringPushup(),common.pallof("2 × 10 per side")]),
  session(13,"Stability","Carry Introduction","25 min","Introduce light carries without aggressive loading or lateral leaning.",[common.sidePlank("2 × 20 sec per side"),common.carry("2 × 15 sec per side","very light"),common.rdl("2 × 6 per side"),common.birdDog(),common.calfRaise()]),
  session(14,"Recovery","Week 2 Recovery","15 min","Restore ease before the next strength phase.",[common.reset(),common.hipMobility(),common.bridge("2 × 8"),common.deadBug("2 × 6 per side")]),
  session(15,"Strength","Hinge & Hip Thrust","30 min","Increase posterior-chain strength with stable hip positions.",[common.hipThrust("3 × 10"),common.rdl("3 × 6 per side"),common.ringRow("3 × 10"),common.sidePlank("2 × 25 sec per side"),common.calfRaise("3 × 12")]),
  session(16,"Elasticity / Jump Preparation","Landing Position Practice","20 min","Introduce quiet landing mechanics before any larger jump demand.",[common.hipMobility(),common.landing(),common.stepDown("2 × 6 per side"),common.balance(),common.tibRaise("2 × 12")]),
  session(17,"Stability","Lateral Strength Control","25 min","Progress lateral control and anti-rotation strength at a manageable dose.",[common.sidePlank("3 × 20 sec per side",false),common.pallof("3 × 8 per side"),common.lateralStep(),common.carry("2 × 20 sec per side","light"),common.deadBug("2 × 8 per side")]),
  session(18,"Recovery","Mobility Reset","15 min","Keep movement comfortable and easy between strength sessions.",[common.reset(),common.hipMobility(),common.bridge("2 × 10"),common.birdDog("2 × 6 per side")]),
  session(19,"Strength","Unilateral Strength B","35 min","Build range and reps in controlled single-leg patterns.",[common.splitSquat("3 × 8 per side"),common.rdl("3 × 7 per side"),common.stepUp("3 × 8 per side"),common.ringPushup("3 × 6"),common.ringRow("3 × 8")]),
  session(20,"Elasticity / Jump Preparation","Ankle Spring Preparation","20 min","Build ankle strength and rehearse low-level elastic contacts.",[common.calfRaise("3 × 12"),common.tibRaise("3 × 12"),common.landing("3 × 5"),common.pogo("2 × 8"),common.sidePlank("2 × 20 sec per side",false)]),
  session(21,"Recovery","Week 3 Recovery","15 min","Reduce effort and prepare for the final strength week.",[common.reset(),common.hipMobility(),common.deadBug("2 × 6 per side"),common.balance("2 × 20 sec per side")]),
  session(22,"Strength","Strength & Carry","35 min","Add modest carry time after stable strength positions are established.",[common.hipThrust("3 × 10"),common.splitSquat("3 × 8 per side"),common.carry("3 × 20 sec per side","light to moderate"),common.ringRow("3 × 10"),common.pallof("3 × 10 per side")]),
  session(23,"Stability","Single-Leg Range Control","30 min","Use controlled range and balance to reinforce hip and trunk control.",[common.stepDown("3 × 7 per side","low-to-medium"),common.rdl("3 × 8 per side"),common.lateralStep("3 × 6 per side"),common.sidePlank("3 × 25 sec per side",false),common.calfRaise("3 × 12")]),
  session(24,"Recovery","Movement Quality Reset","15 min","Recover while preserving comfortable motion and control.",[common.reset(),common.hipMobility(),common.bridge("2 × 10"),common.birdDog("2 × 8 per side")]),
  session(25,"Elasticity / Jump Preparation","Low-Level Elastic Control","25 min","Progress low-level elasticity only through quiet, consistent contacts.",[common.landing("3 × 5"),common.pogo("3 × 10"),common.stepUp("2 × 8 per side"),common.tibRaise("3 × 12"),common.deadBug("2 × 8 per side")]),
  session(26,"Strength","Full-Body Strength Control","35 min","Connect lower-body strength, trunk control, and rings work without rushing load.",[common.hipThrust("3 × 10"),common.rdl("3 × 8 per side"),common.ringPushup("3 × 8"),common.ringRow("3 × 10"),common.farmerCarry("2 × 25 sec")]),
  session(27,"Movement","Lateral Movement Readiness","25 min","Practice lateral control and stable single-leg transitions.",[common.lateralStep("3 × 8 per side"),common.stepDown("3 × 8 per side","low-to-medium"),common.pallof("3 × 10 per side"),common.balance("2 × 30 sec per side"),common.calfRaise("3 × 12")]),
  session(28,"Recovery","Week 4 Recovery","15 min","Arrive at the final sessions rested and attentive to quality.",[common.reset(),common.hipMobility(),common.sidePlank("2 × 20 sec per side",false),common.bridge("2 × 10")]),
  session(29,"Performance Preparation","Controlled Power Preparation","30 min","Combine unilateral strength, quiet landings, and low-level elastic work with control.",[common.splitSquat("3 × 8 per side"),common.rdl("3 × 8 per side"),common.landing("3 × 5"),common.pogo("3 × 10"),common.carry("2 × 25 sec per side","light to moderate")]),
  session(30,"Performance Preparation","Readiness Assessment","30 min","Review consistent movement quality across balance, strength, landing, and trunk control.",[common.balance("2 × 30 sec per side"),common.stepDown("2 × 8 per side","low-to-medium"),common.sidePlank("2 × 30 sec per side",false),common.landing("3 × 5"),common.pogo("2 × 10"),common.ringRow("2 × 10")]),
];
const restoreMonth1 = { id: "restore-month-1", title: "30-Day Foundation", weeks: [
  { name: "Week 1 · Restore & Activate", workouts: days.slice(0, 7) }, { name: "Week 2 · Build Stability", workouts: days.slice(7, 14) }, { name: "Week 3 · Strength & Elasticity", workouts: days.slice(14, 21) }, { name: "Week 4 · Strength & Power Prep", workouts: days.slice(21, 28) }, { name: "Days 29–30 · Performance Preparation", workouts: days.slice(28) },
] };
const phase2DayDrafts = [
  session(31,"Strength A","Lower Strength & Clean + Press","40 min","Begin progressive strength work with controlled lower-body loading, trunk position, and a manageable clean and press.",[common.hipThrust("3 × 8"),common.splitSquat("3 × 6 per side"),common.cleanPress("3 × 5 per side"),common.ringRow("3 × 8"),common.pallof("2 × 10 per side")]),
  session(32,"Stability","Single-Leg & Lateral Stability","30 min","Build hip and lateral trunk control before adding more range or load.",[common.sidePlank("3 × 20 sec per side",false),common.rdl("3 × 6 per side"),common.stepDown("3 × 6 per side","low-to-medium"),common.carry("3 × 20 sec per side","light to moderate"),common.birdDog("2 × 8 per side")]),
  session(33,"Recovery","Phase 2 Mobility Reset","15 min","Keep movement easy and restore readiness between strength sessions.",[common.reset(),common.hipMobility(),common.bridge("2 × 8"),common.deadBug("2 × 6 per side")]),
  session(34,"Upper Body / Rings","Rings Push, Pull & Arms","35 min","Build controlled upper-body pushing, pulling, and arm strength with rings.",[common.ringRow("3 × 10"),common.ringPushup("3 × 8"),common.ringCurl("2 × 8"),common.ringTriceps("2 × 8"),common.farmerCarry("2 × 30 sec")]),
  session(35,"Movement / Elasticity","Elasticity Foundations","25 min","Continue low-volume elastic preparation with quiet, symmetrical contacts.",[common.calfRaise("3 × 12"),common.landing("3 × 5"),common.pogo("3 × 10"),common.lateralStep("2 × 8 per side"),common.sidePlank("2 × 25 sec per side",false)]),
  session(36,"Strength B","Hinge, Step-Up & Press","40 min","Develop posterior-chain and single-leg strength with a smooth overhead press progression.",[common.rdl("3 × 7 per side"),common.stepUp("3 × 8 per side"),common.cleanPress("3 × 5 per side"),common.ringCloseGrip("3 × 6"),common.carry("2 × 25 sec per side","moderate")]),
  session(37,"Recovery","Week 5 Recovery","15 min","Recover with comfortable mobility and low-effort trunk control.",[common.reset(),common.hipMobility(),common.birdDog("2 × 6 per side"),common.calfRaise("2 × 10")]),
  session(38,"Strength A","Hip Thrust & Split Squat Build","40 min","Progress lower-body strength through a modest set increase while preserving position.",[common.hipThrust("4 × 8"),common.splitSquat("3 × 8 per side"),common.ringRow("3 × 10"),common.pallof("3 × 10 per side"),common.farmerCarry("3 × 25 sec")]),
  session(39,"Stability","Step Control & Anti-Rotation","30 min","Use controlled single-leg range and anti-rotation work to maintain a level pelvis and trunk.",[common.stepDown("3 × 7 per side","medium"),common.lateralStep("3 × 8 per side"),common.sidePlank("3 × 25 sec per side",false),common.pallof("3 × 10 per side"),common.birdDog("3 × 6 per side")]),
  session(40,"Recovery","Easy Movement Reset","15 min","Let fatigue settle while maintaining comfortable movement quality.",[common.reset(),common.hipMobility(),common.bridge("2 × 10"),common.balance("2 × 20 sec per side")]),
  session(41,"Upper Body / Rings","Rings Strength & Arms","40 min","Add a small amount of upper-body volume while keeping rings and bodyweight as the main accessory tools.",[common.ringPushup("3 × 8"),common.ringRow("3 × 10"),common.ringCurl("3 × 8"),common.ringTriceps("3 × 8"),common.barbellCurl("2 × 8")]),
  session(42,"Movement / Elasticity","Low-Volume Elastic Build","25 min","Progress elastic contacts gradually through low volume and landing quality.",[common.landing("3 × 5"),common.pogo("3 × 12"),common.calfRaise("3 × 12"),common.tibRaise("3 × 12"),common.stepUp("2 × 8 per side")]),
  session(43,"Strength B","Posterior Chain & Carry","40 min","Build posterior-chain, pressing, and carry strength without turning the session into conditioning.",[common.rdl("3 × 8 per side"),common.hipThrust("3 × 10"),common.cleanPress("4 × 4 per side"),common.ringCloseGrip("3 × 7"),common.carry("3 × 25 sec per side","moderate")]),
  session(44,"Recovery","Week 6 Recovery","15 min","Recover before the next loading progression.",[common.reset(),common.hipMobility(),common.deadBug("2 × 8 per side"),common.sidePlank("2 × 20 sec per side",false)]),
  session(45,"Strength A","Loaded Lower Strength","45 min","Introduce a manageable external load to lower-body work while keeping quality ahead of load.",[common.hipThrust("4 × 8"),common.splitSquat("4 × 6 per side"),common.stepDown("3 × 8 per side","medium"),common.ringRow("3 × 10"),common.pallof("3 × 12 per side")]),
  session(46,"Stability","Single-Leg Hinge & Lateral Control","35 min","Progress unilateral range and lateral control with a level pelvis and controlled trunk.",[common.rdl("3 × 8 per side"),common.lateralStep("3 × 8 per side"),common.sidePlank("3 × 30 sec per side",false),common.carry("3 × 30 sec per side","moderate"),common.birdDog("3 × 8 per side")]),
  session(47,"Recovery","Mobility & Trunk Reset","15 min","Keep the recovery day genuinely easy while maintaining trunk awareness.",[common.reset(),common.hipMobility(),common.bridge("2 × 10"),common.deadBug("2 × 6 per side")]),
  session(48,"Upper Body / Rings","Overhead & Ring Accessories","40 min","Develop smooth overhead strength with ring-based upper-body accessories.",[common.cleanPress("4 × 5 per side"),common.ringPushup("3 × 10"),common.ringRow("3 × 12"),common.ringCurl("3 × 10"),common.ringTriceps("3 × 10")]),
  session(49,"Movement / Elasticity","Landing & Pogo Control","25 min","Maintain low-volume jump preparation through quiet landings and symmetrical takeoffs.",[common.landing("3 × 6"),common.pogo("4 × 10"),common.calfRaise("3 × 15"),common.stepDown("2 × 8 per side","medium"),common.balance("2 × 25 sec per side")]),
  session(50,"Strength B","Step-Up, Hinge & Carry","45 min","Build single-leg and posterior-chain strength with controlled carry work.",[common.stepUp("3 × 10 per side"),common.rdl("4 × 6 per side"),common.ringCloseGrip("3 × 8"),common.farmerCarry("3 × 30 sec"),common.pallof("3 × 12 per side")]),
  session(51,"Recovery","Week 7 Recovery","15 min","Restore ease and prepare for the final week of this block.",[common.reset(),common.hipMobility(),common.birdDog("2 × 8 per side"),common.calfRaise("2 × 12")]),
  session(52,"Strength A","Strength & Power Technique","45 min","Practice a controlled strength/power clean and press alongside progressive lower-body strength.",[common.cleanPress("4 × 5 per side"),common.hipThrust("4 × 10"),common.splitSquat("3 × 8 per side"),common.ringRow("3 × 12"),common.carry("3 × 30 sec per side","moderate")]),
  session(53,"Stability","Lateral Strength Quality","35 min","Reinforce lateral trunk and hip stability with quality before added load.",[common.sidePlank("3 × 30 sec per side",false),common.stepDown("3 × 8 per side","medium"),common.lateralStep("3 × 10 per side"),common.pallof("3 × 12 per side"),common.birdDog("3 × 8 per side")]),
  session(54,"Recovery","Phase 2 Recovery","15 min","Reduce effort, maintain comfortable range, and arrive fresh for the final strength sessions.",[common.reset(),common.hipMobility(),common.bridge("2 × 10"),common.deadBug("2 × 8 per side")]),
  session(55,"Upper Body / Rings","Rings Push, Pull & Arms Build","40 min","Finish the upper-body progression with controlled rings strength, arms, and trunk position.",[common.ringPushup("3 × 10"),common.ringRow("4 × 10"),common.ringCurl("3 × 10"),common.ringTriceps("3 × 10"),common.barbellCurl("2 × 10")]),
  session(56,"Movement / Elasticity","Elasticity Readiness","25 min","Use only crisp, low-volume contacts; quality determines whether to progress.",[common.landing("3 × 6"),common.pogo("4 × 12"),common.tibRaise("3 × 15"),common.lateralStep("2 × 10 per side"),common.sidePlank("2 × 30 sec per side",false)]),
  session(57,"Strength B","Full-Body Strength Build","45 min","Connect lower-body strength, overhead work, rings, and carries in a controlled final build session.",[common.rdl("4 × 7 per side"),common.stepUp("3 × 10 per side"),common.cleanPress("4 × 5 per side"),common.ringCloseGrip("3 × 8"),common.farmerCarry("3 × 35 sec")]),
  session(58,"Recovery","Strength & Build Check-In","20 min","Consolidate the block with easy movement, stability, and a quality check rather than a hard test.",[common.reset(),common.hipMobility(),common.birdDog("2 × 8 per side"),common.sidePlank("2 × 25 sec per side",false),common.balance("2 × 30 sec per side")]),
];
const phase2Days = phase2DayDrafts.map((workout) => ({ ...workout, id: `strength-build-phase-2-day-${workout.day}` }));
const strengthBuild = { id: "strength-build-phase-2", title: "Phase 2 — Strength & Build", weeks: [
  { name: "Week 5 · Strength Transition", workouts: phase2Days.slice(0, 7) }, { name: "Week 6 · Build Strength", workouts: phase2Days.slice(7, 14) }, { name: "Week 7 · Load & Control", workouts: phase2Days.slice(14, 21) }, { name: "Week 8 · Strength & Build", workouts: phase2Days.slice(21, 28) },
] };
const programPhases = [restoreMonth1, strengthBuild];
const allDays = [...days, ...phase2Days];
const legacyWorkoutDays = {
  "restore-phase-a": 1, "restore-week-1-b": 2, "restore-week-1-c": 3,
  "restore-week-2-a": 8, "restore-week-2-b": 9, "restore-week-2-c": 10,
  "restore-week-3-a": 15, "restore-week-3-b": 16, "restore-week-3-c": 17,
  "restore-week-4-a": 22, "restore-week-4-b": 23, "restore-week-4-c": 24,
};
let currentExercise = 0; let activeWorkout = null;
function getWorkouts() { return programPhases.flatMap((phase) => phase.weeks.flatMap((week,index) => week.workouts.map((workout) => ({ workout, program:phase, week:index+1, weekName:week.name })))); }
function getWorkoutDetails(workoutId) { return getWorkouts().find(({workout}) => workout.id === workoutId); }
function getHistory() {
  try {
    return (JSON.parse(localStorage.getItem(historyKey)) || []).map((completion) => {
      const legacyDay = legacyWorkoutDays[completion.workoutId];
      return legacyDay ? { ...completion, day: completion.day || legacyDay, workoutId: `restore-month-1-day-${legacyDay}` } : completion;
    }).sort((a,b) => new Date(b.completedAt)-new Date(a.completedAt));
  } catch { return []; }
}
function getProgramCompletions() { return getHistory().filter((completion) => programPhases.some((phase) => completion.programId === phase.id)); }
function getTodayWorkout() {
  const completed = new Set(getProgramCompletions().map((completion) => completion.workoutId));
  return allDays.find((workout) => !completed.has(workout.id)) || allDays.at(-1);
}
function recordCompletion(workout) { const details=getWorkoutDetails(workout.id); const history=getHistory(); history.push({ programId:details?.program.id || restoreMonth1.id, day:workout.day, workoutId:workout.id, completedAt:new Date().toISOString(), ...(details ? {week:details.week}: {}) }); localStorage.setItem(historyKey,JSON.stringify(history)); }
function formatDate(value) { return new Date(value).toLocaleDateString(); }
function formatTime(value) { return new Date(value).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}); }
function getTodayCompletion(workout) { return getHistory().find((completion) => completion.workoutId===workout.id && new Date(completion.completedAt).toDateString()===new Date().toDateString()); }
function renderProgramProgress() {
  const completions = getProgramCompletions();
  const completionByWorkoutId = new Map(completions.map((completion) => [completion.workoutId, completion]));
  return `<section class="program-progress"><h3>Training Plan</h3>${programPhases.map((phase) => `<section class="program-phase"><h4>${phase.title}</h4><p>${phase === restoreMonth1 ? "Days 1–30" : "Days 31–58"}</p>${phase.weeks.map((week)=>`<div class="program-week"><h4>${week.name}</h4>${week.workouts.map((workout)=>{
    const completion = completionByWorkoutId.get(workout.id);
    return completion
      ? `<button class="program-session is-complete" type="button" data-action="view-history" data-completed-at="${completion.completedAt}">✓ Day ${workout.day}: ${workout.title}<span>View details</span></button>`
      : `<button class="program-session" type="button" data-action="start-workout" data-workout-id="${workout.id}">○ Day ${workout.day}: ${workout.title}<span>Start workout</span></button>`;
  }).join("")}</div>`).join("")}</section>`).join("")}<p class="progress-total">${completionByWorkoutId.size} of ${allDays.length} sessions completed</p></section>`;
}
function renderToday() {
  const workout=getTodayWorkout();
  const completion=getTodayCompletion(workout);
  const programComplete=getProgramCompletions().map((item)=>item.workoutId).filter((id,index,ids)=>ids.indexOf(id)===index).length===allDays.length;
  const action=programComplete
    ? `<button class="primary-button" type="button" data-action="view-history" data-completed-at="${getProgramCompletions().find((item)=>item.workoutId===workout.id)?.completedAt}">View Day 58 Details</button>`
    : '<button class="primary-button" type="button" data-action="start">Start Workout</button>';
  const details = getWorkoutDetails(workout.id);
  return `<section class="screen-card"><p class="day-label">Day ${workout.day} / ${allDays.length}</p><h2>${workout.title}</h2><p>${details?.program.title || workout.type} · ${workout.type}</p><h3>Today's Session</h3><p>Estimated duration: ${workout.estimatedDuration}</p><p>${workout.objective}</p>${programComplete?'<p class="completion-status">✓ Strength & Build complete</p>':""}${completion?`<p class="completion-status">✓ Completed Today</p><p>Completed at ${formatTime(completion.completedAt)}</p>`:""}<h3>Exercises</h3><ul>${workout.exercises.map((item)=>`<li>${item.name}</li>`).join("")}</ul>${action}${renderProgramProgress()}</section>`;
}
function renderHistory() { const history=getHistory(); if(!history.length) return '<section class="screen-card"><h2>History</h2><p>No completed workouts yet.</p></section>'; return `<section class="screen-card"><h2>History</h2><div class="history-list">${history.map((completion)=>{ const details=getWorkoutDetails(completion.workoutId); if(!details) return ""; const day=completion.day||details.workout.day; return `<button class="history-item" type="button" data-action="view-history" data-completed-at="${completion.completedAt}"><strong>${details.workout.title}</strong><span>Day ${day} · ${details.workout.type}</span><span>${formatDate(completion.completedAt)} · ${formatTime(completion.completedAt)}</span></button>`; }).join("")}</div></section>`; }
function showHistorySummary(completedAt) { const completion=getHistory().find((item)=>item.completedAt===completedAt); const details=completion&&getWorkoutDetails(completion.workoutId); if(!details) return showScreen("history"); const {workout}=details; app.innerHTML=`<section class="screen-card history-summary"><p class="day-label">Day ${completion.day||workout.day} · ${workout.type}</p><h2>${workout.title}</h2><p>${workout.objective}</p><p>${formatDate(completion.completedAt)} · ${formatTime(completion.completedAt)}</p>${workout.exercises.map((item)=>`<article class="history-exercise"><h3>${item.name}</h3><p>${item.reps||item.duration}</p><p>${item.description}</p>${item.cue?`<p><strong>Coaching Cue:</strong> ${item.cue}</p>`:""}${item.tip?`<p><strong>Tip:</strong> ${item.tip}</p>`:""}</article>`).join("")}<button class="primary-button" type="button" data-action="history">Back to History</button></section>`; }
const screens={library:"<h2>Library</h2><p>Coming Soon</p>",settings:"<h2>Settings</h2><p>Coming Soon</p>"};
function showScreen(screen) { app.innerHTML=screen==="today"?renderToday():screen==="history"?renderHistory():screens[screen]; navigation.querySelectorAll("[data-screen]").forEach((button)=>button.toggleAttribute("aria-current",button.dataset.screen===screen)); }
function setWorkoutMode(isActive) { navigation.classList.toggle("is-hidden",isActive); }
function startWorkout(workout) { activeWorkout=workout; currentExercise=0; setWorkoutMode(true); showWorkoutPlayer(activeWorkout); }
function showWorkoutPlayer(workout) { const exercises=workout.exercises; const item=exercises[currentExercise]; const progress=((currentExercise+1)/exercises.length)*100; app.innerHTML=`<section class="workout-player"><p class="workout-title">Day ${workout.day} · ${workout.title}</p><div class="workout-progress" role="progressbar" aria-label="Workout progress" aria-valuemin="1" aria-valuemax="${exercises.length}" aria-valuenow="${currentExercise+1}"><span style="width: ${progress}%"></span></div><p class="exercise-count">Exercise ${currentExercise+1} of ${exercises.length}</p><article class="exercise-card"><h2>${item.name}</h2><p class="exercise-reps">${item.reps||item.duration}</p><section class="exercise-section"><h3>Description</h3><p>${item.description}</p></section>${item.cue?`<section class="exercise-section"><h3>Focus</h3><p>${item.cue}</p></section>`:""}${item.tip?`<section class="exercise-section"><h3>Tip</h3><p>${item.tip}</p></section>`:""}</article><div class="player-actions"><button type="button" data-action="exit">Exit Workout</button><button type="button" data-action="previous" ${currentExercise===0?"disabled":""}>Previous</button><button class="primary-button" type="button" data-action="${currentExercise===exercises.length-1?"finish":"next"}">${currentExercise===exercises.length-1?"Finish Workout":"Next"}</button></div></section>`; }
function showExitDialog() { app.innerHTML+='<div class="modal-backdrop" role="presentation"><section class="exit-dialog" role="dialog" aria-modal="true" aria-labelledby="exit-title"><h2 id="exit-title">Exit Workout?</h2><p>This workout will not be marked as complete.</p><p>You can always start it again later.</p><button class="primary-button" type="button" data-action="continue">Continue Workout</button><button class="text-button" type="button" data-action="confirm-exit">Exit Workout</button></section></div>'; }
function endWorkout() { activeWorkout=null; currentExercise=0; setWorkoutMode(false); showScreen("today"); }
navigation.addEventListener("click",(event)=>{ if(activeWorkout) return; const screen=event.target.dataset.screen; if(screen) showScreen(screen); });
app.addEventListener("click",(event)=>{ const target=event.target.closest("[data-action]"); if(!target) return; if(target.dataset.action==="start") startWorkout(getTodayWorkout()); if(target.dataset.action==="start-workout"){ const details=getWorkoutDetails(target.dataset.workoutId); if(details) startWorkout(details.workout); } if(target.dataset.action==="previous"&&currentExercise>0){currentExercise-=1;showWorkoutPlayer(activeWorkout);} if(target.dataset.action==="next"){currentExercise+=1;showWorkoutPlayer(activeWorkout);} if(target.dataset.action==="finish"){recordCompletion(activeWorkout);endWorkout();} if(target.dataset.action==="exit")showExitDialog(); if(target.dataset.action==="continue")showWorkoutPlayer(activeWorkout); if(target.dataset.action==="confirm-exit")endWorkout(); if(target.dataset.action==="history")showScreen("history"); if(target.dataset.action==="view-history")showHistorySummary(target.dataset.completedAt); });
showScreen("today");
